### PR TITLE
WIP: Dependency upgrade, testing, code cleanup and move to MMP

### PR DESCRIPTION
**Pull request by zbateson**
This is a work-in-progress to get this library moved to using zbateson/MailMimeParser, tested and cleaned up a bit.

I don't intend to add much functionality at this point.  I'll leave a comment when it's ready for a review and eventual merge.

### CODE REVIEW

**Comment by zbateson** [comment]
Okay, I think I'm good for now.  Let me know if there's anything amiss when you have a chance to review.

Cheers :)

**Comment by mnapoli** [comment]
Hi @zbateson thanks for all that work. Honestly I don't know what to do with this PR, there is so many changes I don't know what it's for and it makes it very hard to review.

A few things I noted:

- are you renaming public methods? Those could be BC breaks, which we don't want unless they are very useful
- you seem to have added a lot of phpdoc that duplicates existing type-hints, could you remove those as they are not useful (but please keep any comment/phpdoc that adds information that doesn't exist in the code, those are very useful!)
- there seem to be quite a few code style changes, could you revert those unless they are useful in specific places? (except the `src/Query` directory which seems to have been contributed in a PR but not correctly formatted, it's a good thing to fix this although fitting it all in one PR is hard to review)

Btw the tests are awesome!

**Comment by zbateson** [comment]
Hi @mnapoli 

Sorry I kind of meant this to just be a general "push" for this project, and as it's labeled experimental and not yet on a 1.0 I didn't think bc compatibility would matter.  I probably should've touched base before and checked if this is something you would've wanted.

> are you renaming public methods? Those could be BC breaks, which we don't want unless they are very useful

Yes, I've renamed getEmailsFromId, because it takes an array of IDs, to getEmailsFromIds.  Similarly I've renamed setFlags to setFlag since it only sets a single flag.  I've also changed the name of the second argument to $set and gave it a "bool" type hint instead of $value which I thought was more confusing.

For these, would you prefer I:

1. Rename them back directly, or;
2. Add an alias function with the original name and set it as "deprecated"?

> you seem to have added a lot of phpdoc that duplicates existing type-hints

True and good point... my IDE creates the type-hints automatically when I insert a docblock comment for a method.  I shall remove and look into whether or not phpdoc now allows "@return [description]" as well if php return type-hinting is used.

> there seem to be quite a few code style changes

Sorry for the big PR.  Do you want me to keep those changes aside and submit them separately?

> unless they are useful in specific places? (except the src/Query directory which seems to have been contributed in a PR...)

You mean you want to keep all changes I've made to src/Query?  Or completely revert that?

> Btw the tests are awesome!

It's a starting point at least, right? :)

**Comment by mnapoli** [comment]
OK let's try something else! Are you using (or will you be using) that library? Are you interested in maintaining it?

The thing with BC breaks and all that stuff is that you have to remember to tag a new version, keep the documentation up to date, etc. That doesn't seem much but I have many projects to track so I try to minimize the amount of work I have to do ^^

Since you have plans for this project and they seem very sensible (coding style issues are really the last of my worries if the rest is moving in a great direction) so it would probably be easier if you merge PR and tag versions yourself.

A few things worth following if you are up for it:

- with `0.x.y` version numbers, you can break BC by incrementing `x`. So you can break BC if you tag a new `0.3.0` version. Else keep BC between "patch" versions.
- please add new changes through pull requests, avoid pushing to master (but merge them yourself and don't wait for me, I often review quickly but don't spend much time reviewing everything)

Interested?

**Comment by zbateson** [comment]
I had to give this one some thought.

I'm not currently using it, nor do I have any projects in my pipeline that would need to use it at this point.  I wouldn't mind being a maintainer on it, and every so often could contribute to it as time comes... but, like you I'm not sure how much time that would be or how often unfortunately... so I'm not sure that's what you're looking for.

**Comment by mnapoli** [comment]
Right I understand of course. What's really important for a project is to have a consistent vision and direction, it must not become an addition of features/changes by different users on top of another. I've done that mistake in the past and unfortunately maintaining, and most of all restoring order and removing bloat in a project is very hard and time-consuming. I don't want to be maintaining huge chunks of code and features from different people, and I think it makes for a poor product.

If you have small pull requests that fix specific bugs or change very specific things feel free to send them though.

**Comment by zbateson** [comment]
For sure, totally understand and agree :) cheers @mnapoli

**Pull request closed without merging**
